from transforms.api import transform, Output
import pandas as pd

@transform(
    output=Output("/UNITE/Unit Harmonization/invalid_units_of_measure")
)

def my_compute_function(output):
    '''
    Below is a list of invalid units from sites per codeset.
    These units will be nulled out during the unit inference and harmonization process such that unit inference is performed.
    '''
    invalid_units = [
        {'measured_variable':'Albumin (g/dL)','codeset_id':'104464584','omop_unit_concept_id':'8505','omop_unit_concept_name':'hour'},
        {'measured_variable':'Albumin (g/dL)','codeset_id':'104464584','omop_unit_concept_id':'8577','omop_unit_concept_name':'nanometer'},
        {'measured_variable':'Albumin (g/dL)','codeset_id':'104464584','omop_unit_concept_id':'8587','omop_unit_concept_name':'milliliter'},
        {'measured_variable':'Albumin (g/dL)','codeset_id':'104464584','omop_unit_concept_id':'9648','omop_unit_concept_name':'unified atomic mass unit'},
        {'measured_variable':'Albumin (g/dL)','codeset_id':'104464584','omop_unit_concept_id':'3195322','omop_unit_concept_name':'milligram'},
        {'measured_variable':'Albumin (g/dL)','codeset_id':'104464584','omop_unit_concept_id':'3196676','omop_unit_concept_name':'gram'},
        {'measured_variable':'Albumin (g/dL)','codeset_id':'104464584','omop_unit_concept_id':'8504','omop_unit_concept_name':'gram'},
        {'measured_variable':'Albumin (g/dL)','codeset_id':'104464584','omop_unit_concept_id':'8519','omop_unit_concept_name':'liter'},
        {'measured_variable':'Albumin (g/dL)','codeset_id':'104464584','omop_unit_concept_id':'8554','omop_unit_concept_name':'percent'},
        {'measured_variable':'Albumin (g/dL)','codeset_id':'104464584','omop_unit_concept_id':'8576','omop_unit_concept_name':'milligram'},
        {'measured_variable':'Albumin (g/dL)','codeset_id':'104464584','omop_unit_concept_id':'9245','omop_unit_concept_name':'per deciliter'},
        {'measured_variable':'ALT (SGPT), IU/L','codeset_id':'538737057','omop_unit_concept_id':'8505','omop_unit_concept_name':'hour'},
        {'measured_variable':'ALT (SGPT), IU/L','codeset_id':'538737057','omop_unit_concept_id':'8519','omop_unit_concept_name':'liter'},
        {'measured_variable':'ALT (SGPT), IU/L','codeset_id':'538737057','omop_unit_concept_id':'8543','omop_unit_concept_name':'ampere'},
        {'measured_variable':'ALT (SGPT), IU/L','codeset_id':'538737057','omop_unit_concept_id':'8554','omop_unit_concept_name':'percent'},
        {'measured_variable':'ALT (SGPT), IU/L','codeset_id':'538737057','omop_unit_concept_id':'8587','omop_unit_concept_name':'milliliter'},
        {'measured_variable':'AST (SGOT), IU/L','codeset_id':'248480621','omop_unit_concept_id':'8505','omop_unit_concept_name':'hour'},
        {'measured_variable':'AST (SGOT), IU/L','codeset_id':'248480621','omop_unit_concept_id':'8519','omop_unit_concept_name':'liter'},
        {'measured_variable':'AST (SGOT), IU/L','codeset_id':'248480621','omop_unit_concept_id':'8543','omop_unit_concept_name':'ampere'},
        {'measured_variable':'AST (SGOT), IU/L','codeset_id':'248480621','omop_unit_concept_id':'8577','omop_unit_concept_name':'nanometer'},
        {'measured_variable':'AST (SGOT), IU/L','codeset_id':'248480621','omop_unit_concept_id':'8587','omop_unit_concept_name':'milliliter'},
        {'measured_variable':'Bilirubin (Conjugated/Direct), mg/dL','codeset_id':'50252641','omop_unit_concept_id':'8505','omop_unit_concept_name':'hour'},
        {'measured_variable':'Bilirubin (total), mg/dL','codeset_id':'586434833','omop_unit_concept_id':'8505','omop_unit_concept_name':'hour'},
        {'measured_variable':'Bilirubin (total), mg/dL','codeset_id':'586434833','omop_unit_concept_id':'8577','omop_unit_concept_name':'nanometer'},
        {'measured_variable':'BNP, pg/mL','codeset_id':'703853936','omop_unit_concept_id':'8505','omop_unit_concept_name':'hour'},
        {'measured_variable':'BNP, pg/mL','codeset_id':'703853936','omop_unit_concept_id':'9523','omop_unit_concept_name':'kelvin'},
        {'measured_variable':'BUN, mg/dL','codeset_id':'139231433','omop_unit_concept_id':'8505','omop_unit_concept_name':'hour'},
        {'measured_variable':'BUN, mg/dL','codeset_id':'139231433','omop_unit_concept_id':'8519','omop_unit_concept_name':'liter'},
        {'measured_variable':'BUN, mg/dL','codeset_id':'139231433','omop_unit_concept_id':'8577','omop_unit_concept_name':'nanometer'},
        {'measured_variable':'BUN, mg/dL','codeset_id':'139231433','omop_unit_concept_id':'8554','omop_unit_concept_name':'percent'},
        {'measured_variable':'c-reactive protein CRP, mg/L','codeset_id':'371622342','omop_unit_concept_id':'8505','omop_unit_concept_name':'hour'},
        {'measured_variable':'CD4 Cell Count (absolute)','codeset_id':'24299640','omop_unit_concept_id':'44777549','omop_unit_concept_name':'per square meter'},
        {'measured_variable':'CD4 Cell Count (absolute)','codeset_id':'24299640','omop_unit_concept_id':'8554','omop_unit_concept_name':'percent'},
        {'measured_variable':'CD4 Cell Count (absolute)','codeset_id':'24299640','omop_unit_concept_id':'8564','omop_unit_concept_name':'picogram'},
        {'measured_variable':'CD4 Cell Count (absolute)','codeset_id':'24299640','omop_unit_concept_id':'8577','omop_unit_concept_name':'nanometer'},
        {'measured_variable':'CD4 Cell Count (absolute)','codeset_id':'24299640','omop_unit_concept_id':'8583','omop_unit_concept_name':'femtoliter'},
        {'measured_variable':'CD4 Cell Count (absolute)','codeset_id':'24299640','omop_unit_concept_id':'8647','omop_unit_concept_name':'per microliter'},
        {'measured_variable':'CD4 Cell Count (absolute)','codeset_id':'24299640','omop_unit_concept_id':'8713','omop_unit_concept_name':'gram per deciliter'},
        {'measured_variable':'CD4 Cell Count (absolute)','codeset_id':'24299640','omop_unit_concept_id':'9255','omop_unit_concept_name':'per square meter'},
        {'measured_variable':'CD4 Cell Count (absolute)','codeset_id':'24299640','omop_unit_concept_id':'8566','omop_unit_concept_name':'thousand'},
        {'measured_variable':'CD4 Cell Count (relative)','codeset_id':'254892302','omop_unit_concept_id':'8577','omop_unit_concept_name':'nanometer'},
        {'measured_variable':'CD4 Cell Count (relative)','codeset_id':'254892302','omop_unit_concept_id':'8647','omop_unit_concept_name':'per microliter'},
        {'measured_variable':'CD4 Cell Count (relative)','codeset_id':'254892302','omop_unit_concept_id':'8784','omop_unit_concept_name':'cells per microliter'},
        {'measured_variable':'CD4 Cell Count (relative)','codeset_id':'254892302','omop_unit_concept_id':'8888','omop_unit_concept_name':'cells per cubic millimeter'},
        {'measured_variable':'CD4 Cell Count (relative)','codeset_id':'254892302','omop_unit_concept_id':'9665','omop_unit_concept_name':'microliter'},
        {'measured_variable':'CD4/CD8 Ratio','codeset_id':'410508887','omop_unit_concept_id':'8587','omop_unit_concept_name':'milliliter'},
        {'measured_variable':'CD8 Cell Count (absolute)','codeset_id':'301181605','omop_unit_concept_id':'44777549','omop_unit_concept_name':'per square meter'},
        {'measured_variable':'CD8 Cell Count (absolute)','codeset_id':'301181605','omop_unit_concept_id':'8554','omop_unit_concept_name':'percent'},
        {'measured_variable':'CD8 Cell Count (absolute)','codeset_id':'301181605','omop_unit_concept_id':'9255','omop_unit_concept_name':'per square meter'},
        {'measured_variable':'CD8 Cell Count (relative)','codeset_id':'225952304','omop_unit_concept_id':'8647','omop_unit_concept_name':'per microliter'},
        {'measured_variable':'CD8 Cell Count (relative)','codeset_id':'225952304','omop_unit_concept_id':'8686','omop_unit_concept_name':'cubic millimeter'},
        {'measured_variable':'CD8 Cell Count (relative)','codeset_id':'225952304','omop_unit_concept_id':'9665','omop_unit_concept_name':'microliter'},
        {'measured_variable':'Chloride, mmol/L','codeset_id':'733538531','omop_unit_concept_id':'8505','omop_unit_concept_name':'hour'},
        {'measured_variable':'Chloride, mmol/L','codeset_id':'733538531','omop_unit_concept_id':'8519','omop_unit_concept_name':'liter'},
        {'measured_variable':'Chloride, mmol/L','codeset_id':'733538531','omop_unit_concept_id':'8554','omop_unit_concept_name':'percent'},
        {'measured_variable':'Chloride, mmol/L','codeset_id':'733538531','omop_unit_concept_id':'8577','omop_unit_concept_name':'nanometer'},
        {'measured_variable':'Chloride, mmol/L','codeset_id':'733538531','omop_unit_concept_id':'9573','omop_unit_concept_name':'millimole'},
        {'measured_variable':'Creatinine, mg/dL','codeset_id':'615348047','omop_unit_concept_id':'8505','omop_unit_concept_name':'hour'},
        {'measured_variable':'Creatinine, mg/dL','codeset_id':'615348047','omop_unit_concept_id':'8519','omop_unit_concept_name':'liter'},
        {'measured_variable':'Creatinine, mg/dL','codeset_id':'615348047','omop_unit_concept_id':'8543','omop_unit_concept_name':'ampere'},
        {'measured_variable':'Creatinine, mg/dL','codeset_id':'615348047','omop_unit_concept_id':'8577','omop_unit_concept_name':'nanometer'},
        {'measured_variable':'Creatinine, mg/dL','codeset_id':'615348047','omop_unit_concept_id':'8645','omop_unit_concept_name':'unit per liter'},
        {'measured_variable':'Creatinine, mg/dL','codeset_id':'615348047','omop_unit_concept_id':'9523','omop_unit_concept_name':'kelvin'},
        {'measured_variable':'Creatinine, mg/dL','codeset_id':'615348047','omop_unit_concept_id':'8795','omop_unit_concept_name':'milliliter per minute'},
        {'measured_variable':'D-Dimer, mg/L FEU','codeset_id':'475972797','omop_unit_concept_id':'8587','omop_unit_concept_name':'milliliter'},
        {'measured_variable':'Eosinophils (absolute)','codeset_id':'296867571','omop_unit_concept_id':'8554','omop_unit_concept_name':'percent'},
        {'measured_variable':'Eosinophils (absolute)','codeset_id':'296867571','omop_unit_concept_id':'8566','omop_unit_concept_name':'thousand'},
        {'measured_variable':'Ferritin, ng/mL','codeset_id':'317388455','omop_unit_concept_id':'8505','omop_unit_concept_name':'hour'},
        {'measured_variable':'Ferritin, ng/mL','codeset_id':'317388455','omop_unit_concept_id':'8519','omop_unit_concept_name':'liter'},
        {'measured_variable':'Ferritin, ng/mL','codeset_id':'317388455','omop_unit_concept_id':'8587','omop_unit_concept_name':'milliliter'},
        {'measured_variable':'Glucose, mg/dL','codeset_id':'59698832','omop_unit_concept_id':'8504','omop_unit_concept_name':'gram'},
        {'measured_variable':'Glucose, mg/dL','codeset_id':'59698832','omop_unit_concept_id':'8505','omop_unit_concept_name':'hour'},
        {'measured_variable':'Glucose, mg/dL','codeset_id':'59698832','omop_unit_concept_id':'8519','omop_unit_concept_name':'liter'},
        {'measured_variable':'Glucose, mg/dL','codeset_id':'59698832','omop_unit_concept_id':'8543','omop_unit_concept_name':'ampere'},
        {'measured_variable':'Glucose, mg/dL','codeset_id':'59698832','omop_unit_concept_id':'8550','omop_unit_concept_name':'minute'},
        {'measured_variable':'Glucose, mg/dL','codeset_id':'59698832','omop_unit_concept_id':'8555','omop_unit_concept_name':'second'},
        {'measured_variable':'Glucose, mg/dL','codeset_id':'59698832','omop_unit_concept_id':'8576','omop_unit_concept_name':'milligram'},
        {'measured_variable':'Glucose, mg/dL','codeset_id':'59698832','omop_unit_concept_id':'8577','omop_unit_concept_name':'nanometer'},
        {'measured_variable':'Glucose, mg/dL','codeset_id':'59698832','omop_unit_concept_id':'9211','omop_unit_concept_name':'minute'},
        {'measured_variable':'Glucose, mg/dL','codeset_id':'59698832','omop_unit_concept_id':'9212','omop_unit_concept_name':'second'},
        {'measured_variable':'Hemoglobin A1c, %','codeset_id':'381434987','omop_unit_concept_id':'8505','omop_unit_concept_name':'hour'},
        {'measured_variable':'Hemoglobin A1c, %','codeset_id':'381434987','omop_unit_concept_id':'8543','omop_unit_concept_name':'ampere'},
        {'measured_variable':'Hemoglobin A1c, %','codeset_id':'381434987','omop_unit_concept_id':'8713','omop_unit_concept_name':'gram per deciliter'},
        {'measured_variable':'Hemoglobin A1c, %','codeset_id':'381434987','omop_unit_concept_id':'8840','omop_unit_concept_name':'milligram per deciliter'},
        {'measured_variable':'Hemoglobin, g/dL','codeset_id':'28177118','omop_unit_concept_id':'8504','omop_unit_concept_name':'gram'},
        {'measured_variable':'Hemoglobin, g/dL','codeset_id':'28177118','omop_unit_concept_id':'8505','omop_unit_concept_name':'hour'},
        {'measured_variable':'Hemoglobin, g/dL','codeset_id':'28177118','omop_unit_concept_id':'8519','omop_unit_concept_name':'liter'},
        {'measured_variable':'Hemoglobin, g/dL','codeset_id':'28177118','omop_unit_concept_id':'8543','omop_unit_concept_name':'ampere'},
        {'measured_variable':'Hemoglobin, g/dL','codeset_id':'28177118','omop_unit_concept_id':'8554','omop_unit_concept_name':'percent'},
        {'measured_variable':'Hemoglobin, g/dL','codeset_id':'28177118','omop_unit_concept_id':'8555','omop_unit_concept_name':'second'},
        {'measured_variable':'Hemoglobin, g/dL','codeset_id':'28177118','omop_unit_concept_id':'8576','omop_unit_concept_name':'milligram'},
        {'measured_variable':'Hemoglobin, g/dL','codeset_id':'28177118','omop_unit_concept_id':'8577','omop_unit_concept_name':'nanometer'},
        {'measured_variable':'Hemoglobin, g/dL','codeset_id':'28177118','omop_unit_concept_id':'9212','omop_unit_concept_name':'second'},
        {'measured_variable':'Hemoglobin, g/dL','codeset_id':'28177118','omop_unit_concept_id':'8587','omop_unit_concept_name':'milliliter'},
        {'measured_variable':'HIV Viral Load','codeset_id':'776696816','omop_unit_concept_id':'8587','omop_unit_concept_name':'milliliter'},
        {'measured_variable':'Lactate, U/L','codeset_id':'400660753','omop_unit_concept_id':'8505','omop_unit_concept_name':'hour'},
        {'measured_variable':'Lactate, U/L','codeset_id':'400660753','omop_unit_concept_id':'8519','omop_unit_concept_name':'liter'},
        {'measured_variable':'Lactate, U/L','codeset_id':'400660753','omop_unit_concept_id':'8554','omop_unit_concept_name':'percent'},
        {'measured_variable':'Lymphocytes (absolute), x10E3/uL','codeset_id':'627523060','omop_unit_concept_id':'8645','omop_unit_concept_name':'unit per liter'},
        {'measured_variable':'Lymphocytes (absolute), x10E3/uL','codeset_id':'627523060','omop_unit_concept_id':'8792','omop_unit_concept_name':'Kelvin per microliter'},
        {'measured_variable':'Lymphocytes (absolute), x10E3/uL','codeset_id':'627523060','omop_unit_concept_id':'8938','omop_unit_concept_name':'thousandth per microliter'},
        {'measured_variable':'Lymphocytes (absolute), x10E3/uL','codeset_id':'627523060','omop_unit_concept_id':'9665','omop_unit_concept_name':'microliter'},
        {'measured_variable':'Lymphocytes (absolute), x10E3/uL','codeset_id':'627523060','omop_unit_concept_id':'8554','omop_unit_concept_name':'percent'},
        {'measured_variable':'Lymphocytes (absolute), x10E3/uL','codeset_id':'627523060','omop_unit_concept_id':'8566','omop_unit_concept_name':'thousand'},
        {'measured_variable':'Lymphocytes (relative), %','codeset_id':'45416701','omop_unit_concept_id':'8505','omop_unit_concept_name':'hour'},
        {'measured_variable':'Lymphocytes (relative), %','codeset_id':'45416701','omop_unit_concept_id':'8519','omop_unit_concept_name':'liter'},
        {'measured_variable':'Lymphocytes (relative), %','codeset_id':'45416701','omop_unit_concept_id':'8543','omop_unit_concept_name':'ampere'},
        {'measured_variable':'Lymphocytes (relative), %','codeset_id':'45416701','omop_unit_concept_id':'8577','omop_unit_concept_name':'nanometer'},
        {'measured_variable':'Lymphocytes (relative), %','codeset_id':'45416701','omop_unit_concept_id':'8582','omop_unit_concept_name':'centimeter'},
        {'measured_variable':'Lymphocytes (relative), %','codeset_id':'45416701','omop_unit_concept_id':'8587','omop_unit_concept_name':'milliliter'},
        {'measured_variable':'Lymphocytes (relative), %','codeset_id':'45416701','omop_unit_concept_id':'8588','omop_unit_concept_name':'millimeter'},
        {'measured_variable':'Lymphocytes (relative), %','codeset_id':'45416701','omop_unit_concept_id':'8784','omop_unit_concept_name':'cells per microliter'},
        {'measured_variable':'Lymphocytes (relative), %','codeset_id':'45416701','omop_unit_concept_id':'8785','omop_unit_concept_name':'per cubic millimeter'},
        {'measured_variable':'Lymphocytes (relative), %','codeset_id':'45416701','omop_unit_concept_id':'8961','omop_unit_concept_name':'thousand per cubic millimeter'},
        {'measured_variable':'Lymphocytes (relative), %','codeset_id':'45416701','omop_unit_concept_id':'8848','omop_unit_concept_name':'thousand per microliter'},
        {'measured_variable':'Neutrophils (absolute), x10E3/uL','codeset_id':'881397271','omop_unit_concept_id':'8577','omop_unit_concept_name':'nanometer'},
        {'measured_variable':'Neutrophils (absolute), x10E3/uL','codeset_id':'881397271','omop_unit_concept_id':'8645','omop_unit_concept_name':'unit per liter'},
        {'measured_variable':'Neutrophils (absolute), x10E3/uL','codeset_id':'881397271','omop_unit_concept_id':'8792','omop_unit_concept_name':'Kelvin per microliter'},
        {'measured_variable':'Neutrophils (absolute), x10E3/uL','codeset_id':'881397271','omop_unit_concept_id':'8938','omop_unit_concept_name':'thousandth per microliter'},
        {'measured_variable':'Neutrophils (absolute), x10E3/uL','codeset_id':'881397271','omop_unit_concept_id':'9665','omop_unit_concept_name':'microliter'},
        {'measured_variable':'Neutrophils (absolute), x10E3/uL','codeset_id':'881397271','omop_unit_concept_id':'8554','omop_unit_concept_name':'percent'},
        {'measured_variable':'Neutrophils (absolute), x10E3/uL','codeset_id':'881397271','omop_unit_concept_id':'8566','omop_unit_concept_name':'thousand'},
        {'measured_variable':'Neutrophils (relative), %','codeset_id':'304813348','omop_unit_concept_id':'8577','omop_unit_concept_name':'nanometer'},
        {'measured_variable':'Neutrophils (relative), %','codeset_id':'304813348','omop_unit_concept_id':'8587','omop_unit_concept_name':'milliliter'},
        {'measured_variable':'Neutrophils (relative), %','codeset_id':'304813348','omop_unit_concept_id':'8961','omop_unit_concept_name':'thousand per cubic millimeter'},
        {'measured_variable':'Neutrophils (relative), %','codeset_id':'304813348','omop_unit_concept_id':'8848','omop_unit_concept_name':'thousand per microliter'},
        {'measured_variable':'NT pro BNP, pg/mL','codeset_id':'561166072','omop_unit_concept_id':'8587','omop_unit_concept_name':'milliliter'},
        {'measured_variable':'NT pro BNP, pg/mL','codeset_id':'561166072','omop_unit_concept_id':'9523','omop_unit_concept_name':'kelvin'},
        {'measured_variable':'Platelet count, x10E3/uL','codeset_id':'167697906','omop_unit_concept_id':'8505','omop_unit_concept_name':'hour'},
        {'measured_variable':'Platelet count, x10E3/uL','codeset_id':'167697906','omop_unit_concept_id':'8519','omop_unit_concept_name':'liter'},
        {'measured_variable':'Platelet count, x10E3/uL','codeset_id':'167697906','omop_unit_concept_id':'8543','omop_unit_concept_name':'ampere'},
        {'measured_variable':'Platelet count, x10E3/uL','codeset_id':'167697906','omop_unit_concept_id':'8554','omop_unit_concept_name':'percent'},
        {'measured_variable':'Platelet count, x10E3/uL','codeset_id':'167697906','omop_unit_concept_id':'8564','omop_unit_concept_name':'picogram'},
        {'measured_variable':'Platelet count, x10E3/uL','codeset_id':'167697906','omop_unit_concept_id':'8577','omop_unit_concept_name':'nanometer'},
        {'measured_variable':'Platelet count, x10E3/uL','codeset_id':'167697906','omop_unit_concept_id':'8792','omop_unit_concept_name':'Kelvin per microliter'},
        {'measured_variable':'Platelet count, x10E3/uL','codeset_id':'167697906','omop_unit_concept_id':'8938','omop_unit_concept_name':'thousandth per microliter'},
        {'measured_variable':'Platelet count, x10E3/uL','codeset_id':'167697906','omop_unit_concept_id':'9523','omop_unit_concept_name':'kelvin'},
        {'measured_variable':'Platelet count, x10E3/uL','codeset_id':'167697906','omop_unit_concept_id':'9648','omop_unit_concept_name':'unified atomic mass unit'},
        {'measured_variable':'Platelet count, x10E3/uL','codeset_id':'167697906','omop_unit_concept_id':'9665','omop_unit_concept_name':'microliter'},
        {'measured_variable':'Platelet count, x10E3/uL','codeset_id':'167697906','omop_unit_concept_id':'9666','omop_unit_concept_name':'micrometer'},
        {'measured_variable':'Platelet count, x10E3/uL','codeset_id':'167697906','omop_unit_concept_id':'8566','omop_unit_concept_name':'thousand'},
        {'measured_variable':'Platelet count, x10E3/uL','codeset_id':'167697906','omop_unit_concept_id':'8583','omop_unit_concept_name':'femtoliter'},
        {'measured_variable':'Potassium, mmol/L','codeset_id':'622316047','omop_unit_concept_id':'44777603','omop_unit_concept_name':'liter per hour'},
        {'measured_variable':'Potassium, mmol/L','codeset_id':'622316047','omop_unit_concept_id':'8504','omop_unit_concept_name':'gram'},
        {'measured_variable':'Potassium, mmol/L','codeset_id':'622316047','omop_unit_concept_id':'8505','omop_unit_concept_name':'hour'},
        {'measured_variable':'Potassium, mmol/L','codeset_id':'622316047','omop_unit_concept_id':'8519','omop_unit_concept_name':'liter'},
        {'measured_variable':'Potassium, mmol/L','codeset_id':'622316047','omop_unit_concept_id':'8576','omop_unit_concept_name':'milligram'},
        {'measured_variable':'Potassium, mmol/L','codeset_id':'622316047','omop_unit_concept_id':'8577','omop_unit_concept_name':'nanometer'},
        {'measured_variable':'Potassium, mmol/L','codeset_id':'622316047','omop_unit_concept_id':'9523','omop_unit_concept_name':'kelvin'},
        {'measured_variable':'Potassium, mmol/L','codeset_id':'622316047','omop_unit_concept_id':'9648','omop_unit_concept_name':'unified atomic mass unit'},
        {'measured_variable':'Sodium, mmol/L','codeset_id':'887473517','omop_unit_concept_id':'8504','omop_unit_concept_name':'gram'},
        {'measured_variable':'Sodium, mmol/L','codeset_id':'887473517','omop_unit_concept_id':'8505','omop_unit_concept_name':'hour'},
        {'measured_variable':'Sodium, mmol/L','codeset_id':'887473517','omop_unit_concept_id':'8519','omop_unit_concept_name':'liter'},
        {'measured_variable':'Sodium, mmol/L','codeset_id':'887473517','omop_unit_concept_id':'8554','omop_unit_concept_name':'percent'},
        {'measured_variable':'Sodium, mmol/L','codeset_id':'887473517','omop_unit_concept_id':'8576','omop_unit_concept_name':'milligram'},
        {'measured_variable':'Sodium, mmol/L','codeset_id':'887473517','omop_unit_concept_id':'8577','omop_unit_concept_name':'nanometer'},
        {'measured_variable':'Sodium, mmol/L','codeset_id':'887473517','omop_unit_concept_id':'9523','omop_unit_concept_name':'kelvin'},
        {'measured_variable':'Sodium, mmol/L','codeset_id':'887473517','omop_unit_concept_id':'9573','omop_unit_concept_name':'millimole'},
        {'measured_variable':'Temperature','codeset_id':'656562966','omop_unit_concept_id':'9471','omop_unit_concept_name':'coulomb'},
        {'measured_variable':'Temperature','codeset_id':'656562966','omop_unit_concept_id':'8517','omop_unit_concept_name':'Farad'},
        {'measured_variable':'Temperature','codeset_id':'656562966','omop_unit_concept_id':'45744812','omop_unit_concept_name':'cells'},
        {'measured_variable':'Troponin all types, ng/mL','codeset_id':'623367088','omop_unit_concept_id':'8505','omop_unit_concept_name':'hour'},
        {'measured_variable':'Troponin all types, ng/mL','codeset_id':'623367088','omop_unit_concept_id':'8577','omop_unit_concept_name':'nanometer'},
        {'measured_variable':'Troponin all types, ng/mL','codeset_id':'623367088','omop_unit_concept_id':'8587','omop_unit_concept_name':'milliliter'},
        {'measured_variable':'White blood cell count, x10E3/uL','codeset_id':'138719030','omop_unit_concept_id':'8504','omop_unit_concept_name':'gram'},
        {'measured_variable':'White blood cell count, x10E3/uL','codeset_id':'138719030','omop_unit_concept_id':'8505','omop_unit_concept_name':'hour'},
        {'measured_variable':'White blood cell count, x10E3/uL','codeset_id':'138719030','omop_unit_concept_id':'8519','omop_unit_concept_name':'liter'},
        {'measured_variable':'White blood cell count, x10E3/uL','codeset_id':'138719030','omop_unit_concept_id':'8543','omop_unit_concept_name':'ampere'},
        {'measured_variable':'White blood cell count, x10E3/uL','codeset_id':'138719030','omop_unit_concept_id':'8554','omop_unit_concept_name':'percent'},
        {'measured_variable':'White blood cell count, x10E3/uL','codeset_id':'138719030','omop_unit_concept_id':'8566','omop_unit_concept_name':'thousand'},
        {'measured_variable':'White blood cell count, x10E3/uL','codeset_id':'138719030','omop_unit_concept_id':'8577','omop_unit_concept_name':'nanometer'},
        {'measured_variable':'White blood cell count, x10E3/uL','codeset_id':'138719030','omop_unit_concept_id':'8792','omop_unit_concept_name':'Kelvin per microliter'},
        {'measured_variable':'White blood cell count, x10E3/uL','codeset_id':'138719030','omop_unit_concept_id':'8903','omop_unit_concept_name':'Kelvin per cubic millimeter'},
        {'measured_variable':'White blood cell count, x10E3/uL','codeset_id':'138719030','omop_unit_concept_id':'8938','omop_unit_concept_name':'thousandth per microliter'},
        {'measured_variable':'White blood cell count, x10E3/uL','codeset_id':'138719030','omop_unit_concept_id':'9523','omop_unit_concept_name':'kelvin'},
        {'measured_variable':'White blood cell count, x10E3/uL','codeset_id':'138719030','omop_unit_concept_id':'9665','omop_unit_concept_name':'microliter'},
    ]

    df = pd.DataFrame(data={
        'measured_variable': list(map(lambda p: p["measured_variable"], invalid_units)),
        'codeset_id': list(map(lambda p: p["codeset_id"], invalid_units)),
        'omop_unit_concept_id': list(map(lambda p: p["omop_unit_concept_id"], invalid_units)),
        'omop_unit_concept_name': list(map(lambda p: p["omop_unit_concept_name"], invalid_units))
    })

    return output.write_pandas(df)