
CREATE TABLE CONCEPT_DIMENSION  ( 
	CONCEPT_PATH   	VARCHAR2(700 BYTE) NOT NULL,
	CONCEPT_CD     	VARCHAR2(50 BYTE) NOT NULL,
	NAME_CHAR      	VARCHAR2(2000 BYTE) NULL,
	CONCEPT_BLOB   	CLOB NULL,
	UPDATE_DATE    	DATE NULL,
	DOWNLOAD_DATE  	DATE NULL,
	IMPORT_DATE    	DATE NULL,
	SOURCESYSTEM_CD	VARCHAR2(50 BYTE) NULL,
	UPLOAD_ID      	NUMBER(38) NULL 
	)
GO

CREATE TABLE OBSERVATION_FACT  ( 
	ENCOUNTER_NUM   	NUMBER(38) NOT NULL,
	PATIENT_NUM     	NUMBER(38) NOT NULL,
	CONCEPT_CD      	VARCHAR2(50 BYTE) NOT NULL,
	PROVIDER_ID     	VARCHAR2(50 BYTE) NOT NULL,
	START_DATE      	DATE NOT NULL,
	MODIFIER_CD     	VARCHAR2(100 BYTE) NOT NULL,
	INSTANCE_NUM    	NUMBER(18) NOT NULL,
	VALTYPE_CD      	VARCHAR2(50 BYTE) NULL,
	TVAL_CHAR       	VARCHAR2(255 BYTE) NULL,
	NVAL_NUM        	NUMBER(18,5) NULL,
	VALUEFLAG_CD    	VARCHAR2(50 BYTE) NULL,
	QUANTITY_NUM    	NUMBER(18,5) NULL,
	UNITS_CD        	VARCHAR2(50 BYTE) NULL,
	END_DATE        	DATE NULL,
	LOCATION_CD     	VARCHAR2(50 BYTE) NULL,
	OBSERVATION_BLOB	CLOB NULL,
	CONFIDENCE_NUM  	NUMBER(18,5) NULL,
	UPDATE_DATE     	DATE NULL,
	DOWNLOAD_DATE   	DATE NULL,
	IMPORT_DATE     	DATE NULL,
	SOURCESYSTEM_CD 	VARCHAR2(50 BYTE) NULL,
	UPLOAD_ID       	NUMBER(38) NULL 
	)
GO


CREATE TABLE PATIENT_DIMENSION  ( 
	PATIENT_NUM      	NUMBER(38) NOT NULL,
	VITAL_STATUS_CD  	VARCHAR2(50 BYTE) NULL,
	BIRTH_DATE       	DATE NULL,
	DEATH_DATE       	DATE NULL,
	SEX_CD           	VARCHAR2(50 BYTE) NULL,
	ETHNICITY_CD     	VARCHAR2(50 BYTE) NULL,
	LANGUAGE_CD      	VARCHAR2(50 BYTE) NULL,
	RACE_CD          	VARCHAR2(50 BYTE) NULL,
	MARITAL_STATUS_CD	VARCHAR2(50 BYTE) NULL,
	RELIGION_CD      	VARCHAR2(50 BYTE) NULL,
	ZIP_CD           	VARCHAR2(10 BYTE) NULL,
	STATECITYZIP_PATH	VARCHAR2(700 BYTE) NULL,
	PATIENT_BLOB     	CLOB NULL,
	UPDATE_DATE      	DATE NULL,
	DOWNLOAD_DATE    	DATE NULL,
	IMPORT_DATE      	DATE NULL,
	SOURCESYSTEM_CD  	VARCHAR2(50 BYTE) NULL,
	UPLOAD_ID        	NUMBER(38) NULL 
	)
GO


CREATE TABLE VISIT_DIMENSION  ( 
	ENCOUNTER_NUM   	NUMBER(38) NOT NULL,
	PATIENT_NUM     	NUMBER(38) NOT NULL,
	ACTIVE_STATUS_CD	VARCHAR2(50 BYTE) NULL,
	START_DATE      	DATE NULL,
	END_DATE        	DATE NULL,
	SCHD_DATE       	DATE NULL,
	ADMIT_DATE      	DATE NULL,
	DSCH_DATE       	DATE NULL,
	ACCMDN_CD       	VARCHAR2(50 BYTE) NULL,
	DSCH_DISP_CD    	VARCHAR2(50 BYTE) NULL,
	DSCH_STAT_CD    	VARCHAR2(50 BYTE) NULL,
	ENC_TYPE_CD     	VARCHAR2(50 BYTE) NULL,
	HSP_SVC_CD      	VARCHAR2(50 BYTE) NULL,
	VISIT_STATUS_CD 	VARCHAR2(50 BYTE) NULL,
	ADT_STATUS_CD   	VARCHAR2(50 BYTE) NULL,
	INOUT_CD        	VARCHAR2(50 BYTE) NULL,
	LOCATION_CD     	VARCHAR2(50 BYTE) NULL,
	LOCATION_PATH   	VARCHAR2(900 BYTE) NULL,
	LENGTH_OF_STAY  	NUMBER(38) NULL,
	VISIT_BLOB      	CLOB NULL,
	UPDATE_DATE     	DATE NULL,
	DOWNLOAD_DATE   	DATE NULL,
	IMPORT_DATE     	DATE NULL,
	SOURCESYSTEM_CD 	VARCHAR2(50 BYTE) NULL,
	UPLOAD_ID       	NUMBER(38) NULL 
	)
GO


CREATE TABLE PROVIDER_DIMENSION  ( 
	PROVIDER_ID    	VARCHAR2(50 BYTE) NOT NULL,
	PROVIDER_PATH  	VARCHAR2(700 BYTE) NOT NULL,
	NAME_CHAR      	VARCHAR2(850 BYTE) NULL,
	PROVIDER_BLOB  	CLOB NULL,
	UPDATE_DATE    	DATE NULL,
	DOWNLOAD_DATE  	DATE NULL,
	IMPORT_DATE    	DATE NULL,
	SOURCESYSTEM_CD	VARCHAR2(50 BYTE) NULL,
	UPLOAD_ID      	NUMBER(38) NULL 
	)
GO
