/************************************************************
project : N3C DI&H
Date: 5/16/2020
Authors: 
Stephanie Hong, 
File : ETHNICITY_XWALK.sql
Description :
Edit History:
  Ver   Date         Author     Description
  0.1	8/30/20      SHONG	    Update from Initial version.
*************************************************************/
CREATE TABLE CDMH_STAGING.ETHNICITY_XWALK 
(
  CDM_NAME VARCHAR2(100 BYTE) 
, CDM_TBL VARCHAR2(100 BYTE) 
, SRC_ETHNICITY VARCHAR2(100 BYTE) 
, FHIR_CD VARCHAR2(100 BYTE) 
, TARGET_CONCEPT_ID NUMBER(*, 0) NOT NULL 
, TARGET_CONCEPT_NAME VARCHAR2(255 BYTE) NOT NULL 
, TARGET_DOMAIN_ID VARCHAR2(20 BYTE) NOT NULL 
, TARGET_VOCABULARY_ID VARCHAR2(20 BYTE) NOT NULL 
, TARGET_CONCEPT_CLASS_ID VARCHAR2(20 BYTE) NOT NULL 
, TARGET_STANDARD_CONCEPT VARCHAR2(1 BYTE) 
, TARGET_CONCEPT_CODE VARCHAR2(50 BYTE) NOT NULL 
) 
;
Insert into CDMH_STAGING.ETHNICITY_XWALK (CDM_NAME,CDM_TBL,SRC_ETHNICITY,FHIR_CD,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE) values ('I2B2ACT','PATIENT_DIMENSION','DEM|HISP:NI','No Information',46237210,'No Information','Ethnicity','Ethnicity','Ethnicity','S','NI');
Insert into CDMH_STAGING.ETHNICITY_XWALK (CDM_NAME,CDM_TBL,SRC_ETHNICITY,FHIR_CD,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE) values ('PCORnet','DEMOGRAPHIC','Y','2135-2',38003563,'Hispanic or Latino','Ethnicity','Ethnicity','Ethnicity','S','Hispanic');
Insert into CDMH_STAGING.ETHNICITY_XWALK (CDM_NAME,CDM_TBL,SRC_ETHNICITY,FHIR_CD,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE) values ('PCORnet','DEMOGRAPHIC','N','2186-5',38003564,'Not Hispanic or Latino','Ethnicity','Ethnicity','Ethnicity','S','Not Hispanic');
Insert into CDMH_STAGING.ETHNICITY_XWALK (CDM_NAME,CDM_TBL,SRC_ETHNICITY,FHIR_CD,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE) values ('PCORnet','DEMOGRAPHIC','NI','No Information',46237210,'No Information','Ethnicity','Ethnicity','Ethnicity','S','NI');
Insert into CDMH_STAGING.ETHNICITY_XWALK (CDM_NAME,CDM_TBL,SRC_ETHNICITY,FHIR_CD,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE) values ('PCORnet','DEMOGRAPHIC','OT','Other',45878142,'Other','Ethnicity','Ethnicity','Ethnicity','S','OT');
Insert into CDMH_STAGING.ETHNICITY_XWALK (CDM_NAME,CDM_TBL,SRC_ETHNICITY,FHIR_CD,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE) values ('PCORnet','DEMOGRAPHIC','R','Refuse to answer',0,'Refuse to answer','Ethnicity','Ethnicity','Ethnicity','S','R');
Insert into CDMH_STAGING.ETHNICITY_XWALK (CDM_NAME,CDM_TBL,SRC_ETHNICITY,FHIR_CD,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE) values ('PCORnet','DEMOGRAPHIC','UN','Unknown',45877986,'Unknown','Ethnicity','Ethnicity','Ethnicity','S','UN');
Insert into CDMH_STAGING.ETHNICITY_XWALK (CDM_NAME,CDM_TBL,SRC_ETHNICITY,FHIR_CD,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE) values ('I2B2ACT','PATIENT_DIMENSION','DEM|HISP:Y','2135-2',38003563,'Hispanic or Latino','Ethnicity','Ethnicity','Ethnicity','S','Hispanic');
Insert into CDMH_STAGING.ETHNICITY_XWALK (CDM_NAME,CDM_TBL,SRC_ETHNICITY,FHIR_CD,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE) values ('I2B2ACT','PATIENT_DIMENSION','DEM|HISP:N','2186-5',38003564,'Not Hispanic or Latino','Ethnicity','Ethnicity','Ethnicity','S','Not Hispanic');
