/************************************************************
project : N3C DI&H
Date: 5/16/2020
Authors: 
Stephanie Hong, 
File : GENDER_XWALK.sql
Description :
Edit History:
  Ver   Date         Author     Description
  0.1	8/30/20      SHONG	    Update from Initial version.
  0.2   9/14/20      SHONG 		Most recent update. 
*************************************************************/

CREATE TABLE CDMH_STAGING.GENDER_XWALK 
(
  CDM_NAME VARCHAR2(100 BYTE) 
, CDM_TBL VARCHAR2(100 BYTE) 
, SRC_GENDER VARCHAR2(20 BYTE) 
, FHIR_CD VARCHAR2(100 BYTE) 
, TARGET_CONCEPT_ID NUMBER(*, 0) NOT NULL 
, TARGET_CONCEPT_NAME VARCHAR2(255 BYTE) NOT NULL 
, TARGET_DOMAIN_ID VARCHAR2(20 BYTE) NOT NULL 
, TARGET_VOCABULARY_ID VARCHAR2(20 BYTE) NOT NULL 
, TARGET_CONCEPT_CLASS_ID VARCHAR2(20 BYTE) NOT NULL 
, TARGET_STANDARD_CONCEPT VARCHAR2(1 BYTE) 
, TARGET_CONCEPT_CODE VARCHAR2(50 BYTE) NOT NULL 
) 
;
Insert into CDMH_STAGING.GENDER_XWALK (CDM_NAME,CDM_TBL,SRC_GENDER,FHIR_CD,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE) values ('PCORnet','DEMOGRAPHIC','M','male',8507,'MALE','Gender','Gender','Gender','S','M');
Insert into CDMH_STAGING.GENDER_XWALK (CDM_NAME,CDM_TBL,SRC_GENDER,FHIR_CD,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE) values ('PCORnet','DEMOGRAPHIC','F','female',8532,'FEMALE','Gender','Gender','Gender','S','F');
Insert into CDMH_STAGING.GENDER_XWALK (CDM_NAME,CDM_TBL,SRC_GENDER,FHIR_CD,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE) values ('PCORnet','DEMOGRAPHIC','A',null,0,'Ambiguous','Gender','Gender','Gender','S','0');
Insert into CDMH_STAGING.GENDER_XWALK (CDM_NAME,CDM_TBL,SRC_GENDER,FHIR_CD,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE) values ('PCORnet','DEMOGRAPHIC','NI','unknown',0,'No Information','Gender','Gender','Gender','S','0');
Insert into CDMH_STAGING.GENDER_XWALK (CDM_NAME,CDM_TBL,SRC_GENDER,FHIR_CD,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE) values ('PCORnet','DEMOGRAPHIC','OT','other',0,'Other','Gender','Gender','Gender','S','0');
Insert into CDMH_STAGING.GENDER_XWALK (CDM_NAME,CDM_TBL,SRC_GENDER,FHIR_CD,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE) values ('PCORnet','DEMOGRAPHIC','UN','unknown',0,'Unknown','Gender','Gender','Gender','S','0');
Insert into CDMH_STAGING.GENDER_XWALK (CDM_NAME,CDM_TBL,SRC_GENDER,FHIR_CD,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE) values ('I2B2ACT','PATIENT_DIMENSION','DEM|SEX:M','male',8507,'Male','Gender','Gender','Gender','S','M');
Insert into CDMH_STAGING.GENDER_XWALK (CDM_NAME,CDM_TBL,SRC_GENDER,FHIR_CD,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE) values ('I2B2ACT','PATIENT_DIMENSION','DEM|SEX:F','female',8532,'FEMALE','Gender','Gender','Gender','S','F');
Insert into CDMH_STAGING.GENDER_XWALK (CDM_NAME,CDM_TBL,SRC_GENDER,FHIR_CD,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE) values ('I2B2ACT','PATIENT_DIMENSION','DEM|SEX:NI','unknown',0,'No Information','Gender','Gender','Gender','S','0');
Insert into CDMH_STAGING.GENDER_XWALK (CDM_NAME,CDM_TBL,SRC_GENDER,FHIR_CD,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE) values ('I2B2ACT','PATIENT_DIMENSION','DEM|SEX:O','Other',0,'Other','Gender','Gender','Gender','S','0');
Insert into CDMH_STAGING.GENDER_XWALK (CDM_NAME,CDM_TBL,SRC_GENDER,FHIR_CD,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE) values ('I2B2ACT','PATIENT_DIMENSION','DEM|SEX:A',null,0,'Ambiguous','Gender','Gender','Gender','S','0');
