/************************************************************
project : N3C DI&H
Date: 5/16/2020
Authors: 
Stephanie Hong, Sandeep Naredla, Richard Zhu, Tanner Zhang
Stored Procedure :
Description :
Edit History:
  Ver   Date    Author  Change History: 
  0.1	5/16/20 shong   Intial version. 
  0.2.  8/30/20 SHONG	Update for v1
*************************************************************/

CREATE TABLE CDMH_STAGING.RACE_XWALK 
(
  CDM_NAME VARCHAR2(100 BYTE) 
, CDM_TBL VARCHAR2(100 BYTE) 
, SRC_RACE VARCHAR2(100 BYTE) 
, FHIR_CD VARCHAR2(100 BYTE) 
, TARGET_CONCEPT_ID NUMBER(*, 0) NOT NULL 
, TARGET_CONCEPT_NAME VARCHAR2(255 BYTE) NOT NULL 
, TARGET_DOMAIN_ID VARCHAR2(20 BYTE) NOT NULL 
, TARGET_VOCABULARY_ID VARCHAR2(20 BYTE) NOT NULL 
, TARGET_CONCEPT_CLASS_ID VARCHAR2(20 BYTE) NOT NULL 
, TARGET_STANDARD_CONCEPT VARCHAR2(1 BYTE) 
, TARGET_CONCEPT_CODE VARCHAR2(50 BYTE) NOT NULL 
) 
;

Insert into CDMH_STAGING.RACE_XWALK (CDM_NAME,CDM_TBL,SRC_RACE,FHIR_CD,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE) values ('PCORnet','DEMOGRAPHIC','06','2131-1',45878142,'Other-multiple race','Race','Race','Race','S','6');
Insert into CDMH_STAGING.RACE_XWALK (CDM_NAME,CDM_TBL,SRC_RACE,FHIR_CD,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE) values ('PCORnet','DEMOGRAPHIC','01','1002-5',8657,'American  Indian  or  Alaska  Native','Race','Race','Race','S','1');
Insert into CDMH_STAGING.RACE_XWALK (CDM_NAME,CDM_TBL,SRC_RACE,FHIR_CD,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE) values ('PCORnet','DEMOGRAPHIC','02','2028-9',8515,'Asian','Race','Race','Race','S','2');
Insert into CDMH_STAGING.RACE_XWALK (CDM_NAME,CDM_TBL,SRC_RACE,FHIR_CD,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE) values ('PCORnet','DEMOGRAPHIC','03','2054-5',8516,'Black  or  African  American','Race','Race','Race','S','3');
Insert into CDMH_STAGING.RACE_XWALK (CDM_NAME,CDM_TBL,SRC_RACE,FHIR_CD,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE) values ('PCORnet','DEMOGRAPHIC','04','2076-8',8557,'Native  Hawaiian  or  Other  Pacific  Islander','Race','Race','Race','S','4');
Insert into CDMH_STAGING.RACE_XWALK (CDM_NAME,CDM_TBL,SRC_RACE,FHIR_CD,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE) values ('PCORnet','DEMOGRAPHIC','05','2106-3',8527,'White','Race','Race','Race','S','5');
Insert into CDMH_STAGING.RACE_XWALK (CDM_NAME,CDM_TBL,SRC_RACE,FHIR_CD,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE) values ('PCORnet','DEMOGRAPHIC','07',null,0,'Refused to Answer','Race','Race','Race','S','7');
Insert into CDMH_STAGING.RACE_XWALK (CDM_NAME,CDM_TBL,SRC_RACE,FHIR_CD,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE) values ('PCORnet','DEMOGRAPHIC','UN','Unknown',45877986,'Unknown','Race','Race','Race','S','UN');
Insert into CDMH_STAGING.RACE_XWALK (CDM_NAME,CDM_TBL,SRC_RACE,FHIR_CD,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE) values ('PCORnet','DEMOGRAPHIC','OT','Other',45878142,'Other','Race','Race','Race','S','OT');
Insert into CDMH_STAGING.RACE_XWALK (CDM_NAME,CDM_TBL,SRC_RACE,FHIR_CD,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE) values ('PCORnet','DEMOGRAPHIC','NI','NI',46237210,'NI','Race','Race','Race','S','NI');
Insert into CDMH_STAGING.RACE_XWALK (CDM_NAME,CDM_TBL,SRC_RACE,FHIR_CD,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE) values ('I2B2ACT','PATIENT_DIMENSION','DEM|RACE:NA','1002-5',8657,'American  Indian  or  Alaska  Native','Race','Race','Race','S','NA');
Insert into CDMH_STAGING.RACE_XWALK (CDM_NAME,CDM_TBL,SRC_RACE,FHIR_CD,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE) values ('I2B2ACT','PATIENT_DIMENSION','DEM|RACE:AS','2028-9',8515,'Asian','Race','Race','Race','S','AS');
Insert into CDMH_STAGING.RACE_XWALK (CDM_NAME,CDM_TBL,SRC_RACE,FHIR_CD,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE) values ('I2B2ACT','PATIENT_DIMENSION','DEM|RACE:B','2054-5',8516,'Black  or  African  American','Race','Race','Race','S','B');
Insert into CDMH_STAGING.RACE_XWALK (CDM_NAME,CDM_TBL,SRC_RACE,FHIR_CD,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE) values ('I2B2ACT','PATIENT_DIMENSION','DEM|RACE:H','2076-8',8557,'Native  Hawaiian  or  Other  Pacific  Islander','Race','Race','Race','S','H');
Insert into CDMH_STAGING.RACE_XWALK (CDM_NAME,CDM_TBL,SRC_RACE,FHIR_CD,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE) values ('I2B2ACT','PATIENT_DIMENSION','DEM|RACE:W','2106-3',8527,'White','Race','Race','Race','S','W');
Insert into CDMH_STAGING.RACE_XWALK (CDM_NAME,CDM_TBL,SRC_RACE,FHIR_CD,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE) values ('I2B2ACT','PATIENT_DIMENSION','DEM|RACE:NI','0',46237210,'NI','Race','Race','Race','S','NI');
