from collections import OrderedDict
from pyspark.sql import types as T


complete_domain_schema_dict = {
    'care_site': OrderedDict([
        ('CARE_SITE_ID', T.LongType()),
        ('CARE_SITE_NAME', T.StringType()),
        ('PLACE_OF_SERVICE_CONCEPT_ID', T.IntegerType()),
        ('LOCATION_ID', T.LongType()),
        ('CARE_SITE_SOURCE_VALUE', T.StringType()),
        ('PLACE_OF_SERVICE_SOURCE_VALUE', T.StringType()),
    ]),
    'condition_era': OrderedDict([
        ('CONDITION_ERA_ID', T.LongType()),
        ('PERSON_ID', T.LongType()),
        ('CONDITION_CONCEPT_ID', T.IntegerType()),
        ('CONDITION_ERA_START_DATE', T.DateType()),
        ('CONDITION_ERA_END_DATE', T.DateType()),
        ('CONDITION_OCCURRENCE_COUNT', T.IntegerType()),
    ]),
    'condition_occurrence': OrderedDict([
        ('CONDITION_OCCURRENCE_ID', T.LongType()),
        ('PERSON_ID', T.LongType()),
        ('CONDITION_CONCEPT_ID', T.IntegerType()),
        ('CONDITION_START_DATE', T.DateType()),
        ('CONDITION_START_DATETIME', T.TimestampType()),
        ('CONDITION_END_DATE', T.DateType()),
        ('CONDITION_END_DATETIME', T.TimestampType()),
        ('CONDITION_TYPE_CONCEPT_ID', T.IntegerType()),
        ('STOP_REASON', T.StringType()),
        ('PROVIDER_ID', T.IntegerType()),
        ('VISIT_OCCURRENCE_ID', T.LongType()),
        ('VISIT_DETAIL_ID', T.IntegerType()),
        ('CONDITION_SOURCE_VALUE', T.StringType()),
        ('CONDITION_SOURCE_CONCEPT_ID', T.IntegerType()),
        ('CONDITION_STATUS_SOURCE_VALUE', T.StringType()),
        ('CONDITION_STATUS_CONCEPT_ID', T.IntegerType()),
    ]),
    'death': OrderedDict([
        ('PERSON_ID', T.LongType()),
        ('DEATH_DATE', T.DateType()),
        ('DEATH_DATETIME', T.TimestampType()),
        ('DEATH_TYPE_CONCEPT_ID', T.IntegerType()),
        ('CAUSE_CONCEPT_ID', T.IntegerType()),
        ('CAUSE_SOURCE_VALUE', T.StringType()),
        ('CAUSE_SOURCE_CONCEPT_ID', T.IntegerType()),
    ]),
    'device_exposure': OrderedDict([
        ('DEVICE_EXPOSURE_ID', T.LongType()),
        ('PERSON_ID', T.LongType()),
        ('DEVICE_CONCEPT_ID', T.IntegerType()),
        ('DEVICE_EXPOSURE_START_DATE', T.DateType()),
        ('DEVICE_EXPOSURE_START_DATETIME', T.TimestampType()),
        ('DEVICE_EXPOSURE_END_DATE', T.DateType()),
        ('DEVICE_EXPOSURE_END_DATETIME', T.TimestampType()),
        ('DEVICE_TYPE_CONCEPT_ID', T.IntegerType()),
        ('UNIQUE_DEVICE_ID', T.StringType()),
        ('QUANTITY', T.IntegerType()),
        ('PROVIDER_ID', T.IntegerType()),
        ('VISIT_OCCURRENCE_ID', T.LongType()),
        ('VISIT_DETAIL_ID', T.IntegerType()),
        ('DEVICE_SOURCE_VALUE', T.StringType()),
        ('DEVICE_SOURCE_CONCEPT_ID', T.IntegerType()),
    ]),
    'dose_era': OrderedDict([
        ('DOSE_ERA_ID', T.LongType()),
        ('PERSON_ID', T.LongType()),
        ('DRUG_CONCEPT_ID', T.IntegerType()),
        ('UNIT_CONCEPT_ID', T.IntegerType()),
        ('DOSE_VALUE', T.FloatType()),
        ('DOSE_ERA_START_DATE', T.DateType()),
        ('DOSE_ERA_END_DATE', T.DateType()),
    ]),
    'drug_era': OrderedDict([
        ('DRUG_ERA_ID', T.LongType()),
        ('PERSON_ID', T.LongType()),
        ('DRUG_CONCEPT_ID', T.IntegerType()),
        ('DRUG_ERA_START_DATE', T.DateType()),
        ('DRUG_ERA_END_DATE', T.DateType()),
        ('DRUG_EXPOSURE_COUNT', T.IntegerType()),
        ('GAP_DAYS', T.IntegerType()),
    ]),
    'drug_exposure': OrderedDict([
        ('DRUG_EXPOSURE_ID', T.LongType()),
        ('PERSON_ID', T.LongType()),
        ('DRUG_CONCEPT_ID', T.IntegerType()),
        ('DRUG_EXPOSURE_START_DATE', T.DateType()),
        ('DRUG_EXPOSURE_START_DATETIME', T.TimestampType()),
        ('DRUG_EXPOSURE_END_DATE', T.DateType()),
        ('DRUG_EXPOSURE_END_DATETIME', T.TimestampType()),
        ('VERBATIM_END_DATE', T.DateType()),
        ('DRUG_TYPE_CONCEPT_ID', T.IntegerType()),
        ('STOP_REASON', T.StringType()),
        ('REFILLS', T.IntegerType()),
        ('QUANTITY', T.FloatType()),
        ('DAYS_SUPPLY', T.IntegerType()),
        ('SIG', T.StringType()),
        ('ROUTE_CONCEPT_ID', T.IntegerType()),
        ('LOT_NUMBER', T.StringType()),
        ('PROVIDER_ID', T.IntegerType()),
        ('VISIT_OCCURRENCE_ID', T.LongType()),
        ('VISIT_DETAIL_ID', T.IntegerType()),
        ('DRUG_SOURCE_VALUE', T.StringType()),
        ('DRUG_SOURCE_CONCEPT_ID', T.IntegerType()),
        ('ROUTE_SOURCE_VALUE', T.StringType()),
        ('DOSE_UNIT_SOURCE_VALUE', T.StringType()),
    ]),
    'location': OrderedDict([
        ('LOCATION_ID', T.LongType()),
        ('ADDRESS_1', T.StringType()),
        ('ADDRESS_2', T.StringType()),
        ('CITY', T.StringType()),
        ('STATE', T.StringType()),
        ('ZIP', T.StringType()),
        ('COUNTY', T.StringType()),
        ('LOCATION_SOURCE_VALUE', T.StringType()),
    ]),
    'measurement': OrderedDict([
        ('MEASUREMENT_ID', T.LongType()),
        ('PERSON_ID', T.LongType()),
        ('MEASUREMENT_CONCEPT_ID', T.IntegerType()),
        ('MEASUREMENT_DATE', T.DateType()),
        ('MEASUREMENT_DATETIME', T.TimestampType()),
        ('MEASUREMENT_TIME', T.StringType()),
        ('MEASUREMENT_TYPE_CONCEPT_ID', T.IntegerType()),
        ('OPERATOR_CONCEPT_ID', T.IntegerType()),
        ('VALUE_AS_NUMBER', T.FloatType()),
        ('VALUE_AS_CONCEPT_ID', T.IntegerType()),
        ('UNIT_CONCEPT_ID', T.IntegerType()),
        ('RANGE_LOW', T.FloatType()),
        ('RANGE_HIGH', T.FloatType()),
        ('PROVIDER_ID', T.IntegerType()),
        ('VISIT_OCCURRENCE_ID', T.LongType()),
        ('VISIT_DETAIL_ID', T.IntegerType()),
        ('MEASUREMENT_SOURCE_VALUE', T.StringType()),
        ('MEASUREMENT_SOURCE_CONCEPT_ID', T.IntegerType()),
        ('UNIT_SOURCE_VALUE', T.StringType()),
        ('VALUE_SOURCE_VALUE', T.StringType()),
    ]),
    'observation': OrderedDict([
        ('OBSERVATION_ID', T.LongType()),
        ('PERSON_ID', T.LongType()),
        ('OBSERVATION_CONCEPT_ID', T.IntegerType()),
        ('OBSERVATION_DATE', T.DateType()),
        ('OBSERVATION_DATETIME', T.TimestampType()),
        ('OBSERVATION_TYPE_CONCEPT_ID', T.IntegerType()),
        ('VALUE_AS_NUMBER', T.FloatType()),
        ('VALUE_AS_STRING', T.StringType()),
        ('VALUE_AS_CONCEPT_ID', T.IntegerType()),
        ('QUALIFIER_CONCEPT_ID', T.IntegerType()),
        ('UNIT_CONCEPT_ID', T.IntegerType()),
        ('PROVIDER_ID', T.IntegerType()),
        ('VISIT_OCCURRENCE_ID', T.LongType()),
        ('VISIT_DETAIL_ID', T.IntegerType()),
        ('OBSERVATION_SOURCE_VALUE', T.StringType()),
        ('OBSERVATION_SOURCE_CONCEPT_ID', T.IntegerType()),
        ('UNIT_SOURCE_VALUE', T.StringType()),
        ('QUALIFIER_SOURCE_VALUE', T.StringType()),
    ]),
    'observation_period': OrderedDict([
        ('OBSERVATION_PERIOD_ID', T.LongType()),
        ('PERSON_ID', T.LongType()),
        ('OBSERVATION_PERIOD_START_DATE', T.DateType()),
        ('OBSERVATION_PERIOD_END_DATE', T.DateType()),
        ('PERIOD_TYPE_CONCEPT_ID', T.IntegerType()),
    ]),
    'payer_plan_period': OrderedDict([
        ('PAYER_PLAN_PERIOD_ID', T.LongType()),
        ('PERSON_ID', T.LongType()),
        ('PAYER_PLAN_PERIOD_START_DATE', T.DateType()),
        ('PAYER_PLAN_PERIOD_END_DATE', T.DateType()),
        ('PAYER_CONCEPT_ID', T.IntegerType()),
        ('PAYER_SOURCE_VALUE', T.StringType()),
        ('PAYER_SOURCE_CONCEPT_ID', T.IntegerType()),
        ('PLAN_CONCEPT_ID', T.IntegerType()),
        ('PLAN_SOURCE_VALUE', T.StringType()),
        ('PLAN_SOURCE_CONCEPT_ID', T.IntegerType()),
        ('SPONSOR_CONCEPT_ID', T.IntegerType()),
        ('SPONSOR_SOURCE_VALUE', T.StringType()),
        ('SPONSOR_SOURCE_CONCEPT_ID', T.IntegerType()),
        ('FAMILY_SOURCE_VALUE', T.StringType()),
        ('STOP_REASON_CONCEPT_ID', T.IntegerType()),
        ('STOP_REASON_SOURCE_VALUE', T.StringType()),
        ('STOP_REASON_SOURCE_CONCEPT_ID', T.IntegerType()),
    ]),
    'person': OrderedDict([
        ('PERSON_ID', T.LongType()),
        ('GENDER_CONCEPT_ID', T.IntegerType()),
        ('YEAR_OF_BIRTH', T.IntegerType()),
        ('MONTH_OF_BIRTH', T.IntegerType()),
        ('DAY_OF_BIRTH', T.IntegerType()),
        ('BIRTH_DATETIME', T.TimestampType()),
        ('RACE_CONCEPT_ID', T.IntegerType()),
        ('ETHNICITY_CONCEPT_ID', T.IntegerType()),
        ('LOCATION_ID', T.LongType()),
        ('PROVIDER_ID', T.IntegerType()),
        ('CARE_SITE_ID', T.IntegerType()),
        ('PERSON_SOURCE_VALUE', T.StringType()),
        ('GENDER_SOURCE_VALUE', T.StringType()),
        ('GENDER_SOURCE_CONCEPT_ID', T.IntegerType()),
        ('RACE_SOURCE_VALUE', T.StringType()),
        ('RACE_SOURCE_CONCEPT_ID', T.IntegerType()),
        ('ETHNICITY_SOURCE_VALUE', T.StringType()),
        ('ETHNICITY_SOURCE_CONCEPT_ID', T.IntegerType()),
    ]),
    'procedure_occurrence': OrderedDict([
        ('PROCEDURE_OCCURRENCE_ID', T.LongType()),
        ('PERSON_ID', T.LongType()),
        ('PROCEDURE_CONCEPT_ID', T.IntegerType()),
        ('PROCEDURE_DATE', T.DateType()),
        ('PROCEDURE_DATETIME', T.TimestampType()),
        ('PROCEDURE_TYPE_CONCEPT_ID', T.IntegerType()),
        ('MODIFIER_CONCEPT_ID', T.IntegerType()),
        ('QUANTITY', T.IntegerType()),
        ('PROVIDER_ID', T.IntegerType()),
        ('VISIT_OCCURRENCE_ID', T.LongType()),
        ('VISIT_DETAIL_ID', T.IntegerType()),
        ('PROCEDURE_SOURCE_VALUE', T.StringType()),
        ('PROCEDURE_SOURCE_CONCEPT_ID', T.IntegerType()),
        ('MODIFIER_SOURCE_VALUE', T.StringType()),
    ]),
    'provider': OrderedDict([
        ('PROVIDER_ID', T.LongType()),
        ('PROVIDER_NAME', T.StringType()),
        ('NPI', T.StringType()),
        ('DEA', T.StringType()),
        ('SPECIALTY_CONCEPT_ID', T.IntegerType()),
        ('CARE_SITE_ID', T.IntegerType()),
        ('YEAR_OF_BIRTH', T.IntegerType()),
        ('GENDER_CONCEPT_ID', T.IntegerType()),
        ('PROVIDER_SOURCE_VALUE', T.StringType()),
        ('SPECIALTY_SOURCE_VALUE', T.StringType()),
        ('SPECIALTY_SOURCE_CONCEPT_ID', T.IntegerType()),
        ('GENDER_SOURCE_VALUE', T.StringType()),
        ('GENDER_SOURCE_CONCEPT_ID', T.IntegerType()),
    ]),
    'visit_occurrence': OrderedDict([
        ('VISIT_OCCURRENCE_ID', T.LongType()),
        ('PERSON_ID', T.LongType()),
        ('VISIT_CONCEPT_ID', T.IntegerType()),
        ('VISIT_START_DATE', T.DateType()),
        ('VISIT_START_DATETIME', T.TimestampType()),
        ('VISIT_END_DATE', T.DateType()),
        ('VISIT_END_DATETIME', T.TimestampType()),
        ('VISIT_TYPE_CONCEPT_ID', T.IntegerType()),
        ('PROVIDER_ID', T.IntegerType()),
        ('CARE_SITE_ID', T.IntegerType()),
        ('VISIT_SOURCE_VALUE', T.StringType()),
        ('VISIT_SOURCE_CONCEPT_ID', T.IntegerType()),
        ('ADMITTING_SOURCE_CONCEPT_ID', T.IntegerType()),
        ('ADMITTING_SOURCE_VALUE', T.StringType()),
        ('DISCHARGE_TO_CONCEPT_ID', T.IntegerType()),
        ('DISCHARGE_TO_SOURCE_VALUE', T.StringType()),
        ('PRECEDING_VISIT_OCCURRENCE_ID', T.IntegerType()),
    ]),
}


required_domain_schema_dict = {
    'care_site': OrderedDict([
        ('CARE_SITE_ID', T.LongType()),
    ]),
    'condition_era': OrderedDict([
        ('CONDITION_ERA_ID', T.LongType()),
        ('PERSON_ID', T.LongType()),
        ('CONDITION_CONCEPT_ID', T.IntegerType()),
        ('CONDITION_ERA_START_DATE', T.DateType()),
        ('CONDITION_ERA_END_DATE', T.DateType()),
    ]),
    'condition_occurrence': OrderedDict([
        ('CONDITION_OCCURRENCE_ID', T.LongType()),
        ('PERSON_ID', T.LongType()),
        ('CONDITION_CONCEPT_ID', T.IntegerType()),
        ('CONDITION_START_DATE', T.DateType()),
        ('CONDITION_TYPE_CONCEPT_ID', T.IntegerType()),
    ]),
    'death': OrderedDict([
        ('PERSON_ID', T.LongType()),
        ('DEATH_DATE', T.DateType()),
        ('DEATH_TYPE_CONCEPT_ID', T.IntegerType()),
    ]),
    'dose_era': OrderedDict([
        ('DOSE_ERA_ID', T.LongType()),
        ('PERSON_ID', T.LongType()),
        ('DRUG_CONCEPT_ID', T.IntegerType()),
        ('UNIT_CONCEPT_ID', T.IntegerType()),
        ('DOSE_VALUE', T.FloatType()),
        ('DOSE_ERA_START_DATE', T.DateType()),
        ('DOSE_ERA_END_DATE', T.DateType()),
    ]),
    'drug_era': OrderedDict([
        ('DRUG_ERA_ID', T.LongType()),
        ('PERSON_ID', T.LongType()),
        ('DRUG_CONCEPT_ID', T.IntegerType()),
        ('DRUG_ERA_START_DATE', T.DateType()),
        ('DRUG_ERA_END_DATE', T.DateType()),
    ]),
    'drug_exposure': OrderedDict([
        ('DRUG_EXPOSURE_ID', T.LongType()),
        ('PERSON_ID', T.LongType()),
        ('DRUG_CONCEPT_ID', T.IntegerType()),
        ('DRUG_EXPOSURE_START_DATE', T.DateType()),
        ('DRUG_EXPOSURE_END_DATE', T.DateType()),
        ('DRUG_TYPE_CONCEPT_ID', T.IntegerType()),
    ]),
    'location': OrderedDict([
        ('LOCATION_ID', T.LongType()),
    ]),
    'measurement': OrderedDict([
        ('MEASUREMENT_ID', T.LongType()),
        ('PERSON_ID', T.LongType()),
        ('MEASUREMENT_CONCEPT_ID', T.IntegerType()),
        ('MEASUREMENT_DATE', T.DateType()),
        ('MEASUREMENT_TYPE_CONCEPT_ID', T.IntegerType()),
    ]),
    'observation': OrderedDict([
        ('OBSERVATION_ID', T.LongType()),
        ('PERSON_ID', T.LongType()),
        ('OBSERVATION_CONCEPT_ID', T.IntegerType()),
        ('OBSERVATION_DATE', T.DateType()),
        ('OBSERVATION_TYPE_CONCEPT_ID', T.IntegerType()),
    ]),
    'observation_period': OrderedDict([
        ('OBSERVATION_PERIOD_ID', T.LongType()),
        ('PERSON_ID', T.LongType()),
        ('OBSERVATION_PERIOD_START_DATE', T.DateType()),
        ('OBSERVATION_PERIOD_END_DATE', T.DateType()),
        ('PERIOD_TYPE_CONCEPT_ID', T.IntegerType()),
    ]),
    'person': OrderedDict([
        ('PERSON_ID', T.LongType()),
        ('GENDER_CONCEPT_ID', T.IntegerType()),
        ('YEAR_OF_BIRTH', T.IntegerType()),
        ('RACE_CONCEPT_ID', T.IntegerType()),
        ('ETHNICITY_CONCEPT_ID', T.IntegerType()),
    ]),
    'procedure_occurrence': OrderedDict([
        ('PROCEDURE_OCCURRENCE_ID', T.LongType()),
        ('PERSON_ID', T.LongType()),
        ('PROCEDURE_CONCEPT_ID', T.IntegerType()),
        ('PROCEDURE_DATE', T.DateType()),
        ('PROCEDURE_TYPE_CONCEPT_ID', T.IntegerType()),
    ]),
    'provider': OrderedDict([
        ('PROVIDER_ID', T.LongType()),
    ]),
    'visit_occurrence': OrderedDict([
        ('VISIT_OCCURRENCE_ID', T.LongType()),
        ('PERSON_ID', T.LongType()),
        ('VISIT_CONCEPT_ID', T.IntegerType()),
        ('VISIT_START_DATE', T.DateType()),
        ('VISIT_END_DATE', T.DateType()),
        ('VISIT_TYPE_CONCEPT_ID', T.IntegerType()),
    ])
}

manifest_schema = T.StructType([
    T.StructField("SITE_ABBREV", T.StringType(), True),
    T.StructField("SITE_NAME", T.StringType(), True),
    T.StructField("CONTACT_NAME", T.StringType(), True),
    T.StructField("CONTACT_EMAIL", T.StringType(), True),
    T.StructField("CDM_NAME", T.StringType(), True),
    T.StructField("CDM_VERSION", T.StringType(), True),
    T.StructField("VOCABULARY_VERSION", T.StringType(), True),
    T.StructField("N3C_PHENOTYPE_YN", T.StringType(), True),
    T.StructField("N3C_PHENOTYPE_VERSION", T.StringType(), True),
    T.StructField("SHIFT_DATE_YN", T.StringType(), True),
    T.StructField("MAX_NUM_SHIFT_DAYS", T.StringType(), True),
    T.StructField("RUN_DATE", T.StringType(), True),
    T.StructField("UPDATE_DATE", T.StringType(), True),
    T.StructField("NEXT_SUBMISSION_DATE", T.StringType(), True),
    T.StructField("CONTRIBUTION_DATE", T.StringType(), True),
])
