from pyspark.sql import types as T


complete_domain_schema_dict = {
    'condition': {
        'CONDITIONID': T.StringType(),
        'PATID': T.StringType(),
        'ENCOUNTERID': T.StringType(),
        'REPORT_DATE': T.DateType(),
        'RESOLVE_DATE': T.DateType(),
        'ONSET_DATE': T.DateType(),
        'CONDITION_STATUS': T.StringType(),
        'CONDITION': T.StringType(),
        'CONDITION_TYPE': T.StringType(),
        'CONDITION_SOURCE': T.StringType(),
        'RAW_CONDITION_STATUS': T.StringType(),
        'RAW_CONDITION': T.StringType(),
        'RAW_CONDITION_TYPE': T.StringType(),
        'RAW_CONDITION_SOURCE': T.StringType(),
    },
    'control_map': {
        "CASE_PATID": T.StringType(),
        "BUDDY_NUM": T.IntegerType(),
        "CONTROL_PATID": T.StringType(),
        "CASE_AGE": T.IntegerType(),
        "CASE_SEX": T.StringType(),
        "CASE_RACE": T.StringType(),
        "CASE_ETHN": T.StringType(),
        "CONTROL_AGE": T.IntegerType(),
        "CONTROL_SEX": T.StringType(),
        "CONTROL_RACE": T.StringType(),
        "CONTROL_ETHN": T.StringType()
    },
    'death': {
        'PATID': T.StringType(),
        'DEATH_DATE': T.DateType(),
        'DEATH_DATE_IMPUTE': T.StringType(),
        'DEATH_SOURCE': T.StringType(),
        'DEATH_MATCH_CONFIDENCE': T.StringType(),
    },
    'death_cause': {
        'PATID': T.StringType(),
        'DEATH_CAUSE': T.StringType(),
        'DEATH_CAUSE_CODE': T.StringType(),
        'DEATH_CAUSE_TYPE': T.StringType(),
        'DEATH_CAUSE_SOURCE': T.StringType(),
        'DEATH_CAUSE_CONFIDENCE': T.StringType(),
    },
    'demographic': {
        'PATID': T.StringType(),
        'BIRTH_DATE': T.DateType(),
        'BIRTH_TIME': T.StringType(),
        'SEX': T.StringType(),
        'SEXUAL_ORIENTATION': T.StringType(),
        'GENDER_IDENTITY': T.StringType(),
        'HISPANIC': T.StringType(),
        'RACE': T.StringType(),
        'BIOBANK_FLAG': T.StringType(),
        'PAT_PREF_LANGUAGE_SPOKEN': T.StringType(),
        'RAW_SEX': T.StringType(),
        'RAW_SEXUAL_ORIENTATION': T.StringType(),
        'RAW_GENDER_IDENTITY': T.StringType(),
        'RAW_HISPANIC': T.StringType(),
        'RAW_RACE': T.StringType(),
        'RAW_PAT_PREF_LANGUAGE_SPOKEN': T.StringType(),
    },
    'diagnosis': {
        'DIAGNOSISID': T.StringType(),
        'PATID': T.StringType(),
        'ENCOUNTERID': T.StringType(),
        'ENC_TYPE': T.StringType(),
        'ADMIT_DATE': T.DateType(),
        'PROVIDERID': T.StringType(),
        'DX': T.StringType(),
        'DX_TYPE': T.StringType(),
        'DX_DATE': T.DateType(),
        'DX_SOURCE': T.StringType(),
        'DX_ORIGIN': T.StringType(),
        'PDX': T.StringType(),
        'DX_POA': T.StringType(),
        'RAW_DX': T.StringType(),
        'RAW_DX_TYPE': T.StringType(),
        'RAW_DX_SOURCE': T.StringType(),
        'RAW_PDX': T.StringType(),
        'RAW_DX_POA': T.StringType(),
    },
    'dispensing': {
        'DISPENSINGID': T.StringType(),
        'PATID': T.StringType(),
        'PRESCRIBINGID': T.StringType(),
        'DISPENSE_DATE': T.DateType(),
        'NDC': T.StringType(),
        'DISPENSE_SOURCE': T.StringType(),
        'DISPENSE_SUP': T.DoubleType(),
        'DISPENSE_AMT': T.DoubleType(),
        'DISPENSE_DOSE_DISP': T.DoubleType(),
        'DISPENSE_DOSE_DISP_UNIT': T.StringType(),
        'DISPENSE_ROUTE': T.StringType(),
        'RAW_NDC': T.StringType(),
        'RAW_DISPENSE_DOSE_DISP': T.StringType(),
        'RAW_DISPENSE_DOSE_DISP_UNIT': T.StringType(),
        'RAW_DISPENSE_ROUTE': T.StringType(),
    },
    'encounter': {
        'ENCOUNTERID': T.StringType(),
        'PATID': T.StringType(),
        'ADMIT_DATE': T.DateType(),
        'ADMIT_TIME': T.StringType(),
        'DISCHARGE_DATE': T.DateType(),
        'DISCHARGE_TIME': T.StringType(),
        'PROVIDERID': T.StringType(),
        'FACILITY_LOCATION': T.StringType(),
        'ENC_TYPE': T.StringType(),
        'FACILITYID': T.StringType(),
        'DISCHARGE_DISPOSITION': T.StringType(),
        'DISCHARGE_STATUS': T.StringType(),
        'DRG': T.StringType(),
        'DRG_TYPE': T.StringType(),
        'ADMITTING_SOURCE': T.StringType(),
        'PAYER_TYPE_PRIMARY': T.StringType(),
        'PAYER_TYPE_SECONDARY': T.StringType(),
        'FACILITY_TYPE': T.StringType(),
        'RAW_SITEID': T.StringType(),
        'RAW_ENC_TYPE': T.StringType(),
        'RAW_DISCHARGE_DISPOSITION': T.StringType(),
        'RAW_DISCHARGE_STATUS': T.StringType(),
        'RAW_DRG_TYPE': T.StringType(),
        'RAW_ADMITTING_SOURCE': T.StringType(),
        'RAW_FACILITY_TYPE': T.StringType(),
        'RAW_PAYER_TYPE_PRIMARY': T.StringType(),
        'RAW_PAYER_NAME_PRIMARY': T.StringType(),
        'RAW_PAYER_ID_PRIMARY': T.StringType(),
        'RAW_PAYER_TYPE_SECONDARY': T.StringType(),
        'RAW_PAYER_NAME_SECONDARY': T.StringType(),
        'RAW_PAYER_ID_SECONDARY': T.StringType(),
    },
    'immunization': {
        'IMMUNIZATIONID': T.StringType(),
        'PATID': T.StringType(),
        'ENCOUNTERID': T.StringType(),
        'PROCEDURESID': T.StringType(),
        'VX_PROVIDERID': T.StringType(),
        'VX_RECORD_DATE': T.DateType(),
        'VX_ADMIN_DATE': T.DateType(),
        'VX_CODE_TYPE': T.StringType(),
        'VX_CODE': T.StringType(),
        'VX_STATUS': T.StringType(),
        'VX_STATUS_REASON': T.StringType(),
        'VX_SOURCE': T.StringType(),
        'VX_DOSE': T.DoubleType(),
        'VX_DOSE_UNIT': T.StringType(),
        'VX_ROUTE': T.StringType(),
        'VX_BODY_SITE': T.StringType(),
        'VX_MANUFACTURER': T.StringType(),
        'VX_LOT_NUM': T.StringType(),
        'VX_EXP_DATE': T.DateType(),
        'RAW_VX_NAME': T.StringType(),
        'RAW_VX_CODE': T.StringType(),
        'RAW_VX_CODE_TYPE': T.StringType(),
        'RAW_VX_DOSE': T.StringType(),
        'RAW_VX_DOSE_UNIT': T.StringType(),
        'RAW_VX_ROUTE': T.StringType(),
        'RAW_VX_BODY_SITE': T.StringType(),
        'RAW_VX_STATUS': T.StringType(),
        'RAW_VX_STATUS_REASON': T.StringType(),
        'RAW_VX_MANUFACTURER': T.StringType(),
    },
    'lab_result_cm': {
        'LAB_RESULT_CM_ID': T.StringType(),
        'PATID': T.StringType(),
        'ENCOUNTERID': T.StringType(),
        'SPECIMEN_SOURCE': T.StringType(),
        'LAB_LOINC': T.StringType(),
        'LAB_RESULT_SOURCE': T.StringType(),
        'LAB_LOINC_SOURCE': T.StringType(),
        'PRIORITY': T.StringType(),
        'RESULT_LOC': T.StringType(),
        'LAB_PX': T.StringType(),
        'LAB_PX_TYPE': T.StringType(),
        'LAB_ORDER_DATE': T.DateType(),
        'SPECIMEN_DATE': T.DateType(),
        'SPECIMEN_TIME': T.StringType(),
        'RESULT_DATE': T.DateType(),
        'RESULT_TIME': T.StringType(),
        'RESULT_QUAL': T.StringType(),
        'RESULT_SNOMED': T.StringType(),
        'RESULT_NUM': T.DoubleType(),
        'RESULT_MODIFIER': T.StringType(),
        'RESULT_UNIT': T.StringType(),
        'NORM_RANGE_LOW': T.StringType(),
        'NORM_MODIFIER_LOW': T.StringType(),
        'NORM_RANGE_HIGH': T.StringType(),
        'NORM_MODIFIER_HIGH': T.StringType(),
        'ABN_IND': T.StringType(),
        'RAW_LAB_NAME': T.StringType(),
        'RAW_LAB_CODE': T.StringType(),
        'RAW_PANEL': T.StringType(),
        'RAW_RESULT': T.StringType(),
        'RAW_UNIT': T.StringType(),
        'RAW_ORDER_DEPT': T.StringType(),
        'RAW_FACILITY_CODE': T.StringType(),
    },
    'lds_address_history': {
        'ADDRESSID': T.StringType(),
        'PATID': T.StringType(),
        'ADDRESS_USE': T.StringType(),
        'ADDRESS_TYPE': T.StringType(),
        'ADDRESS_PREFERRED': T.StringType(),
        'ADDRESS_CITY': T.StringType(),
        'ADDRESS_STATE': T.StringType(),
        'ADDRESS_ZIP5': T.StringType(),
        'ADDRESS_ZIP9': T.StringType(),
        'ADDRESS_PERIOD_START': T.DateType(),
        'ADDRESS_PERIOD_END': T.DateType(),
    },
    'med_admin': {
        'MEDADMINID': T.StringType(),
        'PATID': T.StringType(),
        'ENCOUNTERID': T.StringType(),
        'PRESCRIBINGID': T.StringType(),
        'MEDADMIN_PROVIDERID': T.StringType(),
        'MEDADMIN_START_DATE': T.DateType(),
        'MEDADMIN_START_TIME': T.StringType(),
        'MEDADMIN_STOP_DATE': T.DateType(),
        'MEDADMIN_STOP_TIME': T.StringType(),
        'MEDADMIN_TYPE': T.StringType(),
        'MEDADMIN_CODE': T.StringType(),
        'MEDADMIN_DOSE_ADMIN': T.DoubleType(),
        'MEDADMIN_DOSE_ADMIN_UNIT': T.StringType(),
        'MEDADMIN_ROUTE': T.StringType(),
        'MEDADMIN_SOURCE': T.StringType(),
        'RAW_MEDADMIN_MED_NAME': T.StringType(),
        'RAW_MEDADMIN_CODE': T.StringType(),
        'RAW_MEDADMIN_DOSE_ADMIN': T.StringType(),
        'RAW_MEDADMIN_DOSE_ADMIN_UNIT': T.StringType(),
        'RAW_MEDADMIN_ROUTE': T.StringType(),
    },

    "note": {
        "NOTE_ID": T.LongType(),
        "PERSON_ID": T.StringType(),
        "NOTE_DATE": T.DateType(),
        "NOTE_DATETIME": T.TimestampType(),
        "NOTE_TYPE_CONCEPT_ID": T.IntegerType(),
        "NOTE_CLASS_CONCEPT_ID": T.IntegerType(),
        "NOTE_TITLE": T.StringType(),
        "NOTE_TEXT": T.StringType(),
        "ENCODING_CONCEPT_ID": T.IntegerType(),
        "LANGUAGE_CONCEPT_ID": T.IntegerType(),
        "PROVIDER_ID": T.IntegerType(),
        "VISIT_OCCURRENCE_ID": T.IntegerType(),
        "VISIT_DETAIL_ID": T.IntegerType(),
        "NOTE_SOURCE_VALUE": T.StringType(),
    },

    "note_nlp": {
        "NOTE_NLP_ID": T.LongType(),
        "NOTE_ID": T.LongType(),
        "SECTION_CONCEPT_ID": T.IntegerType(),
        "SNIPPET": T.StringType(),
        "OFFSET": T.StringType(),
        "LEXICAL_VARIANT": T.StringType(),
        "NOTE_NLP_CONCEPT_ID": T.IntegerType(),
        "NOTE_NLP_SOURCE_CONCEPT_ID": T.IntegerType(),
        "NLP_SYSTEM": T.StringType(),
        "NLP_DATE": T.DateType(),
        "NLP_DATETIME": T.TimestampType(),
        "TERM_EXISTS": T.BooleanType(),
        "TERM_TEMPORAL": T.StringType(),
        "TERM_MODIFIERS": T.StringType(),
    },

    'obs_clin': {
        'OBSCLINID': T.StringType(),
        'PATID': T.StringType(),
        'ENCOUNTERID': T.StringType(),
        'OBSCLIN_PROVIDERID': T.StringType(),
        'OBSCLIN_START_DATE': T.DateType(),
        'OBSCLIN_START_TIME': T.StringType(),
        'OBSCLIN_STOP_DATE': T.DateType(),
        'OBSCLIN_STOP_TIME': T.StringType(),
        'OBSCLIN_TYPE': T.StringType(),
        'OBSCLIN_CODE': T.StringType(),
        'OBSCLIN_RESULT_QUAL': T.StringType(),
        'OBSCLIN_RESULT_TEXT': T.StringType(),
        'OBSCLIN_RESULT_SNOMED': T.StringType(),
        'OBSCLIN_RESULT_NUM': T.DoubleType(),
        'OBSCLIN_RESULT_MODIFIER': T.StringType(),
        'OBSCLIN_RESULT_UNIT': T.StringType(),
        'OBSCLIN_SOURCE': T.StringType(),
        'OBSCLIN_ABN_IND': T.StringType(),
        'RAW_OBSCLIN_NAME': T.StringType(),
        'RAW_OBSCLIN_CODE': T.StringType(),
        'RAW_OBSCLIN_TYPE': T.StringType(),
        'RAW_OBSCLIN_RESULT': T.StringType(),
        'RAW_OBSCLIN_MODIFIER': T.StringType(),
        'RAW_OBSCLIN_UNIT': T.StringType(),
    },
    'obs_clin_5.0': {
        'OBSCLINID': T.StringType(),
        'PATID': T.StringType(),
        'ENCOUNTERID': T.StringType(),
        'OBSCLIN_PROVIDERID': T.StringType(),
        'OBSCLIN_DATE': T.DateType(),
        'OBSCLIN_TIME': T.StringType(),
        'OBSCLIN_TYPE': T.StringType(),
        'OBSCLIN_CODE': T.StringType(),
        'OBSCLIN_RESULT_QUAL': T.StringType(),
        'OBSCLIN_RESULT_TEXT': T.StringType(),
        'OBSCLIN_RESULT_SNOMED': T.StringType(),
        'OBSCLIN_RESULT_NUM': T.DoubleType(),
        'OBSCLIN_RESULT_MODIFIER': T.StringType(),
        'OBSCLIN_RESULT_UNIT': T.StringType(),
        'OBSCLIN_SOURCE': T.StringType(),
        'OBSCLIN_ABN_IND': T.StringType(),
        'RAW_OBSCLIN_NAME': T.StringType(),
        'RAW_OBSCLIN_CODE': T.StringType(),
        'RAW_OBSCLIN_TYPE': T.StringType(),
        'RAW_OBSCLIN_RESULT': T.StringType(),
        'RAW_OBSCLIN_MODIFIER': T.StringType(),
        'RAW_OBSCLIN_UNIT': T.StringType(),
    },
    'obs_gen': {
        'OBSGENID': T.StringType(),
        'PATID': T.StringType(),
        'ENCOUNTERID': T.StringType(),
        'OBSGEN_PROVIDERID': T.StringType(),
        'OBSGEN_START_DATE': T.DateType(),
        'OBSGEN_START_TIME': T.StringType(),
        'OBSGEN_STOP_DATE': T.DateType(),
        'OBSGEN_STOP_TIME': T.StringType(),
        'OBSGEN_TYPE': T.StringType(),
        'OBSGEN_CODE': T.StringType(),
        'OBSGEN_RESULT_QUAL': T.StringType(),
        'OBSGEN_RESULT_TEXT': T.StringType(),
        'OBSGEN_RESULT_NUM': T.DoubleType(),
        'OBSGEN_RESULT_MODIFIER': T.StringType(),
        'OBSGEN_RESULT_UNIT': T.StringType(),
        'OBSGEN_TABLE_MODIFIED': T.StringType(),
        'OBSGEN_ID_MODIFIED': T.StringType(),
        'OBSGEN_SOURCE': T.StringType(),
        'OBSGEN_ABN_IND': T.StringType(),
        'RAW_OBSGEN_NAME': T.StringType(),
        'RAW_OBSGEN_CODE': T.StringType(),
        'RAW_OBSGEN_TYPE': T.StringType(),
        'RAW_OBSGEN_RESULT': T.StringType(),
        'RAW_OBSGEN_UNIT': T.StringType(),
    },
    'obs_gen_5.0': {
        'OBSGENID': T.StringType(),
        'PATID': T.StringType(),
        'ENCOUNTERID': T.StringType(),
        'OBSGEN_PROVIDERID': T.StringType(),
        'OBSGEN_DATE': T.DateType(),
        'OBSGEN_TIME': T.StringType(),
        'OBSGEN_TYPE': T.StringType(),
        'OBSGEN_CODE': T.StringType(),
        'OBSGEN_RESULT_QUAL': T.StringType(),
        'OBSGEN_RESULT_TEXT': T.StringType(),
        'OBSGEN_RESULT_NUM': T.DoubleType(),
        'OBSGEN_RESULT_MODIFIER': T.StringType(),
        'OBSGEN_RESULT_UNIT': T.StringType(),
        'OBSGEN_TABLE_MODIFIED': T.StringType(),
        'OBSGEN_ID_MODIFIED': T.StringType(),
        'OBSGEN_SOURCE': T.StringType(),
        'OBSGEN_ABN_IND': T.StringType(),
        'RAW_OBSGEN_NAME': T.StringType(),
        'RAW_OBSGEN_CODE': T.StringType(),
        'RAW_OBSGEN_TYPE': T.StringType(),
        'RAW_OBSGEN_RESULT': T.StringType(),
        'RAW_OBSGEN_UNIT': T.StringType(),
    },
    'prescribing': {
        'PRESCRIBINGID': T.StringType(),
        'PATID': T.StringType(),
        'ENCOUNTERID': T.StringType(),
        'RX_PROVIDERID': T.StringType(),
        'RX_ORDER_DATE': T.DateType(),
        'RX_ORDER_TIME': T.StringType(),
        'RX_START_DATE': T.DateType(),
        'RX_END_DATE': T.DateType(),
        'RX_DOSE_ORDERED': T.DoubleType(),
        'RX_DOSE_ORDERED_UNIT': T.StringType(),
        'RX_QUANTITY': T.DoubleType(),
        'RX_DOSE_FORM': T.StringType(),
        'RX_REFILLS': T.DoubleType(),
        'RX_DAYS_SUPPLY': T.DoubleType(),
        'RX_FREQUENCY': T.StringType(),
        'RX_PRN_FLAG': T.StringType(),
        'RX_ROUTE': T.StringType(),
        'RX_BASIS': T.StringType(),
        'RXNORM_CUI': T.StringType(),
        'RX_SOURCE': T.StringType(),
        'RX_DISPENSE_AS_WRITTEN': T.StringType(),
        'RAW_RX_MED_NAME': T.StringType(),
        'RAW_RX_FREQUENCY': T.StringType(),
        'RAW_RXNORM_CUI': T.StringType(),
        'RAW_RX_QUANTITY': T.StringType(),
        'RAW_RX_NDC': T.StringType(),
        'RAW_RX_DOSE_ORDERED': T.StringType(),
        'RAW_RX_DOSE_ORDERED_UNIT': T.StringType(),
        'RAW_RX_ROUTE': T.StringType(),
        'RAW_RX_REFILLS': T.StringType(),
    },
    'procedures': {
        'PROCEDURESID': T.StringType(),
        'PATID': T.StringType(),
        'ENCOUNTERID': T.StringType(),
        'ENC_TYPE': T.StringType(),
        'ADMIT_DATE': T.DateType(),
        'PROVIDERID': T.StringType(),
        'PX_DATE': T.DateType(),
        'PX': T.StringType(),
        'PX_TYPE': T.StringType(),
        'PX_SOURCE': T.StringType(),
        'PPX': T.StringType(),
        'RAW_PX': T.StringType(),
        'RAW_PX_TYPE': T.StringType(),
        'RAW_PPX': T.StringType(),
    },
    'provider': {
        'PROVIDERID': T.StringType(),
        'PROVIDER_SEX': T.StringType(),
        'PROVIDER_SPECIALTY_PRIMARY': T.StringType(),
        'PROVIDER_NPI': T.DoubleType(),
        'PROVIDER_NPI_FLAG': T.StringType(),
        'RAW_PROVIDER_SPECIALTY_PRIMARY': T.StringType(),
    },
    'pro_cm': {
        'PRO_CM_ID': T.StringType(),
        'PATID': T.StringType(),
        'ENCOUNTERID': T.StringType(),
        'PRO_DATE': T.DateType(),
        'PRO_TIME': T.StringType(),
        'PRO_TYPE': T.StringType(),
        'PRO_ITEM_NAME': T.StringType(),
        'PRO_ITEM_LOINC': T.StringType(),
        'PRO_RESPONSE_TEXT': T.StringType(),
        'PRO_RESPONSE_NUM': T.DoubleType(),
        'PRO_METHOD': T.StringType(),
        'PRO_MODE': T.StringType(),
        'PRO_CAT': T.StringType(),
        'PRO_SOURCE': T.StringType(),
        'PRO_ITEM_VERSION': T.StringType(),
        'PRO_MEASURE_NAME': T.StringType(),
        'PRO_MEASURE_SEQ': T.StringType(),
        'PRO_MEASURE_SCORE': T.DoubleType(),
        'PRO_MEASURE_THETA': T.DoubleType(),
        'PRO_MEASURE_SCALED_TSCORE': T.DoubleType(),
        'PRO_MEASURE_STANDARD_ERROR': T.DoubleType(),
        'PRO_MEASURE_COUNT_SCORED': T.DoubleType(),
        'PRO_MEASURE_LOINC': T.StringType(),
        'PRO_MEASURE_VERSION': T.StringType(),
        'PRO_ITEM_FULLNAME': T.StringType(),
        'PRO_ITEM_TEXT': T.StringType(),
        'PRO_MEASURE_FULLNAME': T.StringType(),
    },
    'vital': {
        'VITALID': T.StringType(),
        'PATID': T.StringType(),
        'ENCOUNTERID': T.StringType(),
        'MEASURE_DATE': T.DateType(),
        'MEASURE_TIME': T.StringType(),
        'VITAL_SOURCE': T.StringType(),
        'HT': T.DoubleType(),
        'WT': T.DoubleType(),
        'DIASTOLIC': T.DoubleType(),
        'SYSTOLIC': T.DoubleType(),
        'ORIGINAL_BMI': T.DoubleType(),
        'BP_POSITION': T.StringType(),
        'SMOKING': T.StringType(),
        'TOBACCO': T.StringType(),
        'TOBACCO_TYPE': T.StringType(),
        'RAW_DIASTOLIC': T.StringType(),
        'RAW_SYSTOLIC': T.StringType(),
        'RAW_BP_POSITION': T.StringType(),
        'RAW_SMOKING': T.StringType(),
        'RAW_TOBACCO': T.StringType(),
        'RAW_TOBACCO_TYPE': T.StringType(),
    },
}


required_domain_schema_dict = {
    'condition': {
        'CONDITIONID': T.StringType(),
        'PATID': T.StringType(),
        'CONDITION': T.StringType(),
        'CONDITION_TYPE': T.StringType(),
        'CONDITION_SOURCE': T.StringType(),
    },
    'control_map': {
        "CASE_PATID": T.StringType(),
        "BUDDY_NUM": T.IntegerType(),
        "CONTROL_PATID": T.StringType()
    },
    'death': {
        'PATID': T.StringType(),
        'DEATH_SOURCE': T.StringType(),
    },
    'death_cause': {
        'PATID': T.StringType(),
        'DEATH_CAUSE': T.StringType(),
        'DEATH_CAUSE_CODE': T.StringType(),
        'DEATH_CAUSE_TYPE': T.StringType(),
        'DEATH_CAUSE_SOURCE': T.StringType(),
    },
    'demographic': {
        'PATID': T.StringType(),
    },
    'diagnosis': {
        'DIAGNOSISID': T.StringType(),
        'PATID': T.StringType(),
        'DX': T.StringType(),
        'DX_TYPE': T.StringType(),
        'DX_SOURCE': T.StringType(),
    },
    'dispensing': {
        'DISPENSINGID': T.StringType(),
        'PATID': T.StringType(),
        'DISPENSE_DATE': T.DateType(),
        'NDC': T.StringType(),
    },
    'encounter': {
        'ENCOUNTERID': T.StringType(),
        'PATID': T.StringType(),
        'ADMIT_DATE': T.DateType(),
        'ENC_TYPE': T.StringType(),
    },
    'immunization': {
        'PATID': T.StringType(),
        'VX_CODE': T.StringType(),
        'VX_CODE_TYPE': T.StringType(),
        'VX_STATUS': T.StringType(),
    },
    'lab_result_cm': {
        'LAB_RESULT_CM_ID': T.StringType(),
        'PATID': T.StringType(),
        'RESULT_DATE': T.DateType(),
    },
    'lds_address_history': {
        'PATID': T.StringType(),
        'ADDRESS_USE': T.StringType(),
        'ADDRESS_TYPE': T.StringType(),
        'ADDRESS_PREFERRED': T.StringType(),
    },
    'med_admin': {
        'MEDADMINID': T.StringType(),
        'PATID': T.StringType(),
        'MEDADMIN_START_DATE': T.DateType(),
    },
    'note': {},
    'note_nlp': {},
    'obs_clin': {
        'OBSCLINID': T.StringType(),
        'PATID': T.StringType(),
        'OBSCLIN_START_DATE': T.DateType(),
    },
    'obs_clin_5.0': {
        'OBSCLINID': T.StringType(),
        'PATID': T.StringType(),
        'OBSCLIN_DATE': T.DateType(),
    },
    'obs_gen': {
        'OBSGENID': T.StringType(),
        'PATID': T.StringType(),
        'OBSGEN_START_DATE': T.DateType(),
    },
    'obs_gen_5.0': {
        'OBSGENID': T.StringType(),
        'PATID': T.StringType(),
        'OBSGEN_DATE': T.DateType(),
    },
    'prescribing': {
        'PRESCRIBINGID': T.StringType(),
        'PATID': T.StringType(),
    },
    'procedures': {
        'PROCEDURESID': T.StringType(),
        'PATID': T.StringType(),
        'PX': T.StringType(),
        'PX_TYPE': T.StringType(),
    },
    'provider': {
        'PROVIDERID': T.StringType(),
    },
    'pro_cm': {
        'PRO_CM_ID': T.StringType(),
        'PATID': T.StringType(),
        'PRO_DATE': T.DateType(),
    },
    'vital': {
        'VITALID': T.StringType(),
        'PATID': T.StringType(),
        'MEASURE_DATE': T.DateType(),
        'VITAL_SOURCE': T.StringType(),
    },
}

data_counts_schema = {
    "TABLE_NAME": T.StringType(),
    "ROW_COUNT": T.StringType()
}

manifest_schema = {
    "SITE_ABBREV": T.StringType(),
    "SITE_NAME": T.StringType(),
    "CONTACT_NAME": T.StringType(),
    "CONTACT_EMAIL": T.StringType(),
    "CDM_NAME": T.StringType(),
    "CDM_VERSION": T.StringType(),
    "VOCABULARY_VERSION": T.StringType(),
    "N3C_PHENOTYPE_YN": T.StringType(),
    "N3C_PHENOTYPE_VERSION": T.StringType(),
    "SHIFT_DATE_YN": T.StringType(),
    "MAX_NUM_SHIFT_DAYS": T.StringType(),
    "RUN_DATE": T.StringType(),
    "UPDATE_DATE": T.StringType(),
    "NEXT_SUBMISSION_DATE": T.StringType(),
}

metadata_schemas = {
    "data_counts": data_counts_schema,
    "manifest": manifest_schema
}
